Search engine
Endermandels/JarOfPickles pull request #3
Opened 2024-11-01 20:49 UTC by thanhdo3764

Implemented basic searching of our data and PageRank into the scoring.

2024-11-04 17:18 UTC, NateShaw2 reviewed
I think the majority of the code is good. I had a question on line 41 of page_rank.py regarding if it is necessary to transpose the adjacency matrix. I was also wondering be better to commit a requirements.txt instead of a venv folder since it would be less bloat.

Also, while testing anime_search_engine.py I found that for the query "tokyo" one of the top 10 pages was a 404 Error page which I found interesting since there was over 100 hits. This might be worth looking into more.

2024-11-05 17:18 UTC, thanhdo3764 commented on page_rank.py
> +	matrix = __adjacency_to_transition_matrix(matrix)
Transposition is necessary for the PageRank logic.

2024-11-05 17:20 UTC, thanhdo3764 commented on page_rank.py
> +	matrix = __adjacency_to_transition_matrix(matrix)
The 404 Error page is an error with the sample, so it should be fine to accept this pull request and change the sample later.

2024-11-05 17:57 UTC, Endermandels requested changes
Overall, the search engine works pretty well.  I would suggest changing all mentions of file names to variables so that the file names are easily changeable in the future.  Great job, Thanh!

2024-11-05 17:57 UTC, Endermandels commented on anime_search_engine.py
> +		htmlParser = None;
I don't think you need this semi colon.

2024-11-05 17:57 UTC, Endermandels commented on anime_search_engine.py
> +		self.ix = self.__get_indexer("./indexdir")
It would be a good idea to have the filenames be optional parameters when initializing the SearchEngine instance.

2024-11-05 17:57 UTC, Endermandels commented on anime_search_engine.py
> +		urls = self.__unpickle("./sample/url_map.dat")
Again, having class variables or function parameters for file names would probably be a good idea.

2024-11-06 21:55 UTC, Endermandels approved these changes
I tested it out, and the search engine still works.  Thank you for switching the hardcoded file names to variables.

2024-11-06 21:55 UTC, merged